
INSERT INTO bar VALUES (1, NULL);
INSERT INTO bar VALUES (2, NULL);
INSERT INTO bar VALUES (3, NULL);
INSERT INTO bar VALUES (4, NULL);
INSERT INTO bar VALUES (5, NULL);
INSERT INTO bar VALUES (6, NULL);
INSERT INTO bar VALUES (7, NULL);
INSERT INTO bar VALUES (8, NULL);
INSERT INTO bar VALUES (9, NULL);
INSERT INTO bar VALUES (10, NULL);



INSERT INTO foo VALUES (1, NULL);
INSERT INTO foo VALUES (2, NULL);
INSERT INTO foo VALUES (3, NULL);
INSERT INTO foo VALUES (4, NULL);
INSERT INTO foo VALUES (5, NULL);
INSERT INTO foo VALUES (6, NULL);
INSERT INTO foo VALUES (7, NULL);
INSERT INTO foo VALUES (8, NULL);
INSERT INTO foo VALUES (9, NULL);
INSERT INTO foo VALUES (10, NULL);

